#! /bin/sh

bspc config border_width        1
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config focused_border_color "#aaaaaa"

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d main browser dwnlds misc msgs
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a pidgin desktop=msgs
bspc rule -a Screenkey manage=off
bspc rule -a obshutdown floating=on

setxkbmap "us,ru" ",winkeys" "grp:alt_shift_toggle" &
xset +fp /usr/share/fonts/artwiz-fonts/ &
xset fp rehash &
nitrogen --restore &
mpd &
compton --config ~/.config/compton &
#pidgin &
panel &
